### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by sidou01** [rby90/project-based-tutorials-in-c#13]
Under the OS section both links **Rewrite cat video** and **Rewrite mkdir** are broken (the [site](https://learnto.computer/) that provides these videos is down).

**Comment by rby90** [comment]
Hey, @sidou01 

I applied my google-fu and managed to find author’s videos on [YouTube](https://www.youtube.com/channel/UCcFVlUyZm22BB6-pPqxZSMg). 

I’m going to give it a week or two before I replace links to see if author brings his site back up.

Thanks for the help!

**Comment by rby90** [comment]
Author's site is still down (for now), going to update/add the additional tutorials (echo/chmod) from author's YouTube. 

However, the "mkdir -p paths" video is missing from there.
