### ISSUE TITLE
How to write a video player in less than 1000 lines is deprecated

### ISSUE THREAD

**Issue by sauntheninja2** [rby90/project-based-tutorials-in-c#18]
That tutorial has only been kept up to date till 2015 even the original author has archived his repository maybe add a deprecated tag?

**Comment by jetejetteraiASAP** [comment]
I'm a little late, but I found an advanced project with video player (actually, a video streamer) as a part of it: https://github.com/pikvm/ustreamer

`pikvm` is a very well-renowned, and mature project. The code base is not for beginners though, which invites deliberation on whether this should be included in this repository. Please take at [this](https://github.com/pikvm/ustreamer/tree/master/src/ustreamer) part of the repo, for the source files of `µStreamer`: although, I'm personally very new to programming in C, I'm sure someone with enough experience can refactor the code here to make a stand-alone video player. Won't be under 1000 lines though, I'm afraid.

Cheers :)

**Comment by rby90** [comment]
I'll add `deprecated`. Thanks for your help!
