### ISSUE TITLE
Difficulty tags? 

### ISSUE THREAD

**Issue by meatnordrink** [rby90/project-based-tutorials-in-c#19]
It seems like it would increase the usefulness of this resource if the various tutorials were tagged with a broad difficulty level. I realize that raises the question of who decides that; but I feel like any sort of indication of relative difficulty would be helpful. As-is, you sort of have to search through and guess which ones might be appropriate to your experience level.

I haven't done many of these, so I'm not qualified yet, but an example would be the Hangman tutorial - perfect for beginners. (Even just a `beginner` tag might be enough.)

Feel free to just close this if the issue's been brought up before (I didn't see it in the closed issues, but I could have missed it).

**Comment by rby90** [comment]
Not a bad idea! However, I am worried about cluttering with too many tags. I'll think about removing some tags such a `video` as maybe it doesn't provide much in weight and going through adding difficulty tags.

**Comment by meatnordrink** [comment]
Thanks so much for considering the idea!
