### ISSUE TITLE
Adding resources for autoconf/Makefiles?

### ISSUE THREAD

**Issue by Gumnos** [rby90/Project-Based-Tutorials-in-C#3]
Makefiles and autoconf are some of the most ad-hoc aspects of C development that could use some best-practices documentation. Any hope this project could include some? I haven't found any really good tutorials or I'd suggest them here.

**Comment by rby90** [comment]
As long as the tutorial builds a project in the process then yeah.

You might try shuffling through the tutorial section on [awesome-c](https://github.com/kozross/awesome-c#learning-reference-and-tutorials).
