### ISSUE TITLE
Handmade Quake is probably abandoned

### ISSUE THREAD

**Issue by Waltarb** [rby90/Project-Based-Tutorials-in-C#4]
This certain tutorial gathered my interest but unfortunately the uploader hasn't made any new videos since April of 2016. It still has some interesting stuff to learn, but maybe put a flag next to it so people know.

This is a great list for getting into C, Cheers!

**Comment by rby90** [comment]
Thanks for pointing this out. It looks like the author [took a new job](https://www.reddit.com/r/HandmadeQuake/comments/4fklxo/my_announcement_is_downright_epic/) which didn't leave him enough time to continue.

I'm going to keep Handmade Quake on the list as you suggested and change the `in-progess` tag to `abandoned`.
