### ISSUE TITLE
All DashGL tutorials are offline

### ISSUE THREAD

**Issue by a20eac1d** [rby90/Project-Based-Tutorials-in-C#6]
Examples include "Astroids Clone" and "Brickout Clone". Maybe find some alternatives, because those were great projects and simply removing them would be sad.

**Comment by MilanDonhowe** [comment]
#7 PR Made to address issue

**Comment by rby90** [comment]
Merged @MilanDonhowe PR thanks!

**Comment by rezaprima** [comment]
Isn't this related to #7? If it fixes this issue, the dead links should not
be removed
